const Service = require('../models/Service');
const Specialization = require('../models/Specialization');

const servicesData = [
    {
        slug: 'mba-admission',
        title: 'MBA Admission',
        subtitle: 'Get admitted to top MBA colleges across India with expert guidance, career counseling, and end-to-end application support.',
        icon: '🎓',
        badge: 'Popular',
        shortDesc: 'Get admitted to top MBA colleges across India with expert guidance on entrance exams, applications, and interviews.',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        heroGradient: 'linear-gradient(135deg, #4f46e5, #7c3aed)',
        navDesc: 'Full-time MBA programs',
        overview: [
            'The Master of Business Administration (MBA) is one of the most sought-after postgraduate degrees globally. An MBA equips you with essential business acumen, leadership skills, and strategic thinking capabilities that top employers value.',
            'At Bschool Bridge, we help you navigate the complex MBA admission landscape — from choosing the right entrance exam and colleges to acing your interviews and securing your seat at a top-ranked institution.',
            "Whether you're targeting IIMs, XLRI, FMS, SP Jain, or any other premier B-school, our expert counselors provide personalized guidance at every step of the journey.",
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with minimum 50% marks (45% for reserved categories)",
            'Valid score in CAT, XAT, GMAT, MAT, CMAT, NMAT, or state-level MBA entrance exams',
            'Final year graduation students can also apply (provisional admission)',
            'Work experience of 0-5 years preferred for most full-time MBA programs',
            'Strong communication skills and leadership potential',
        ],
        highlights: [
            { icon: '🏛️', title: 'Top Colleges', text: 'Access to 200+ AICTE, UGC & NAAC accredited MBA institutions across India.' },
            { icon: '💼', title: 'High Placements', text: 'Average placement package of ₹8-25 LPA at our partner B-schools.' },
            { icon: '🌐', title: 'Global Exposure', text: 'International exchange programs, global certifications, and foreign faculty.' },
            { icon: '📊', title: 'Industry Connect', text: 'Live projects, industry visits, and corporate mentorship programs.' },
            { icon: '🎯', title: 'Specializations', text: 'Finance, Marketing, HR, Operations, IT, Healthcare & more specializations.' },
            { icon: '💰', title: 'Scholarships', text: 'Merit and need-based scholarships covering up to 100% of tuition fees.' },
        ],
        curriculum: [
            'Marketing Management & Consumer Behavior',
            'Financial Management & Corporate Finance',
            'Human Resource Management & Organizational Behavior',
            'Operations Management & Supply Chain',
            'Business Analytics & Data-Driven Decision Making',
            'Strategic Management & Business Policy',
            'Entrepreneurship & Innovation Management',
            'International Business & Global Trade',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Degree Type', value: "Master's Degree" },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, GMAT, MAT' },
            { icon: '💰', label: 'Fee Range', value: '₹5L - ₹25L (Varies)' },
            { icon: '🎯', label: 'Avg. Placement', value: '₹8-25 LPA' },
        ],
        whyChoose: [
            'Globally recognized degree that opens doors to leadership roles across industries',
            'Develops critical thinking, problem-solving, and managerial competencies',
            'Extensive alumni networks that provide lifelong career support and mentorship',
            'Summer internships that provide real-world business experience before graduation',
            'Opportunities for dual specialization to broaden your career options',
            'Strong ROI — MBA graduates see 2-3x salary increase within 2-3 years',
        ],
        sortOrder: 1,
    },
    {
        slug: 'pgdm-admission',
        title: 'PGDM Admission',
        subtitle: 'Pursue a Post Graduate Diploma in Management from AICTE-approved autonomous institutions with industry-relevant curriculum.',
        icon: '📋',
        badge: 'AICTE Approved',
        shortDesc: 'Post Graduate Diploma in Management from AICTE-approved institutions with industry-aligned curriculum.',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #0ea5e9, #06b6d4)',
        heroGradient: 'linear-gradient(135deg, #0ea5e9, #06b6d4)',
        navDesc: 'Post Graduate Diploma',
        overview: [
            'The Post Graduate Diploma in Management (PGDM) is a 2-year postgraduate management program offered by autonomous institutions approved by AICTE. Unlike MBA, which is a degree program offered by universities, PGDM offers more flexibility in curriculum design and industry alignment.',
            'PGDM programs are highly valued by employers because their curriculum is frequently updated to match current industry demands. Top institutions like IIMs, XLRI, MDI, and IMI offer PGDM instead of MBA.',
            'Bschool Bridge helps you identify the best PGDM programs that align with your career aspirations and guides you through every aspect of the admission process.',
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with at least 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, CMAT, MAT, or institution-specific tests',
            'Final year graduation students are eligible to apply',
            'Some institutions require work experience (typically 1-3 years)',
            'Strong academic record and demonstrated leadership abilities',
        ],
        highlights: [
            { icon: '📈', title: 'Industry-Aligned', text: 'Curriculum updated regularly to match current industry trends and market demands.' },
            { icon: '🏅', title: 'AICTE Approved', text: 'All partner institutions are AICTE-approved, ensuring quality education and recognition.' },
            { icon: '🌍', title: 'Global Tie-ups', text: 'International collaborations with foreign universities for student exchange and dual degrees.' },
            { icon: '💼', title: 'Better Placements', text: 'PGDM campuses attract top MNCs and Fortune 500 companies for placements.' },
            { icon: '🎓', title: 'Flexible Curriculum', text: 'Autonomous institutions can design courses based on market demands, not university constraints.' },
            { icon: '🏢', title: 'Corporate Connect', text: 'Regular guest lectures, workshops, and live projects with industry leaders.' },
        ],
        curriculum: [
            'Managerial Economics & Business Environment',
            'Financial Accounting & Financial Management',
            'Marketing Management & Digital Marketing',
            'Human Resource Management & Labor Laws',
            'Business Analytics & Statistics',
            'Operations & Supply Chain Management',
            'Entrepreneurship & New Venture Creation',
            'Strategic Management & Corporate Governance',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (Full-time)' },
            { icon: '📋', label: 'Degree Type', value: 'PG Diploma (AICTE)' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, CMAT, GMAT' },
            { icon: '💰', label: 'Fee Range', value: '₹8L - ₹28L (Varies)' },
            { icon: '🎯', label: 'Avg. Placement', value: '₹10-30 LPA' },
        ],
        whyChoose: [
            'PGDM is offered by top autonomous institutions like IIMs which have more academic freedom',
            'Curriculum is more dynamic and industry-focused compared to traditional MBA programs',
            'Better industry exposure through mandatory summer internships and live projects',
            'PGDM graduates are equally valued (often preferred) by top recruiters',
            'Networking opportunities with industry professionals, alumni, and global faculty',
            'Many PGDM programs offer dual specialization options for broader career scope',
        ],
        sortOrder: 2,
    },
    {
        slug: 'mba-without-cat',
        title: 'MBA Without CAT',
        subtitle: 'Explore top MBA programs that accept scores from MAT, XAT, ATMA, CMAT, GMAT, and other non-CAT entrance exams.',
        icon: '🚀',
        badge: 'No CAT Score',
        shortDesc: 'Explore top MBA colleges that accept MAT, XAT, ATMA, CMAT and other entrance exams beyond CAT.',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        heroGradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
        navDesc: 'Alternative entrance paths',
        overview: [
            "Not everyone cracks the CAT exam, but that doesn't mean your MBA dream has to end there. India has a thriving ecosystem of excellent B-schools that accept scores from alternative entrance exams like MAT, XAT, ATMA, CMAT, GMAT, and several state-level exams.",
            'Many of these institutions offer world-class education, excellent placements, and strong alumni networks — all without requiring a CAT score. Bschool Bridge specializes in helping students identify and get admitted to these high-quality non-CAT MBA programs.',
            'Our expert counselors evaluate your profile and recommend the best entrance exams and B-schools that maximize your chances of admission to a top management program.',
        ],
        eligibility: [
            "Bachelor's degree from a recognized university with minimum 50% aggregate marks",
            'Valid score in MAT, XAT, ATMA, CMAT, GMAT, NMAT, or state-level entrance exams',
            'Some colleges conduct their own entrance tests — we guide you through all options',
            'Final year graduation students are eligible to apply to most programs',
            'Work experience may strengthen your application but is not mandatory for most programs',
        ],
        highlights: [
            { icon: '📝', title: 'Multiple Exams', text: 'Accept scores from MAT, XAT, ATMA, CMAT, GMAT, and state-level exams.' },
            { icon: '🏛️', title: 'Quality Colleges', text: 'NAAC A+ graded and AICTE-approved institutions with excellent infrastructure.' },
            { icon: '💰', title: 'Affordable Fees', text: 'Many non-CAT colleges offer quality MBA at significantly lower fees.' },
            { icon: '📊', title: 'Good Placements', text: 'Partner colleges offer placement packages ranging from ₹5-18 LPA.' },
            { icon: '🔄', title: 'Multiple Intakes', text: 'Some colleges offer multiple admission cycles throughout the year.' },
            { icon: '🎯', title: 'Easy Entrance', text: 'Exams like MAT and ATMA are easier and conducted multiple times a year.' },
        ],
        curriculum: [
            'General Management & Leadership',
            'Marketing Strategy & Brand Management',
            'Financial Planning & Investment Management',
            'Human Capital Management',
            'Operations Excellence & Quality Management',
            'Business Communication & Negotiation Skills',
            'Entrepreneurship & Small Business Management',
            'Business Research Methods & Analytics',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (Full-time)' },
            { icon: '📋', label: 'Degree Type', value: 'MBA / PGDM' },
            { icon: '📍', label: 'Mode', value: 'Full-time / Part-time' },
            { icon: '📝', label: 'Entrance Exams', value: 'MAT, XAT, ATMA, CMAT' },
            { icon: '💰', label: 'Fee Range', value: '₹3L - ₹15L (Varies)' },
            { icon: '🎯', label: 'Avg. Placement', value: '₹5-18 LPA' },
        ],
        whyChoose: [
            'Multiple exam options mean more chances to secure admission every year',
            'MAT/ATMA are conducted 4-5 times a year — you can attempt multiple times',
            'Many excellent B-schools like Symbiosis, Christ, and Alliance accept non-CAT scores',
            'Lower competition compared to CAT-based admissions increases selection chances',
            'GMAT-accepting colleges provide access to internationally recognized programs',
            'Cost-effective education with strong ROI from quality placements',
        ],
        sortOrder: 3,
    },
    {
        slug: 'direct-mba-admission',
        title: 'Direct MBA Admission',
        subtitle: 'Secure your MBA seat directly based on academic merit, work experience, and profile strength — without the stress of competitive entrance exams.',
        icon: '⚡',
        badge: 'Fast Track',
        shortDesc: 'Secure direct admission in management programs based on merit, work experience, and academic performance.',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        heroGradient: 'linear-gradient(135deg, #10b981, #14b8a6)',
        navDesc: 'Fast-track admission',
        overview: [
            'Direct MBA Admission is a streamlined admissions process where students can secure a seat in top management programs based on their academic performance, work experience, and overall profile strength, without solely depending on entrance exam scores.',
            'Many reputed B-schools in India offer management quota, institutional reserved seats, and direct admission pathways for deserving candidates. Bschool Bridge has established partnerships with 100+ colleges that offer legitimate direct admission options.',
            'Our counselors conduct a thorough profile evaluation and connect you with colleges where your profile best fits, ensuring a smooth and transparent admission process.',
        ],
        eligibility: [
            "Bachelor's degree from a recognized university with a minimum of 50% aggregate marks",
            'Entrance exam scores are recommended but not always mandatory for direct admission',
            'Work experience of 1+ years significantly strengthens direct admission applications',
            'Strong academic track record and extracurricular achievements',
            'Statement of Purpose (SOP) and Letters of Recommendation (LOR) may be required',
        ],
        highlights: [
            { icon: '⚡', title: 'Fast Process', text: 'Complete the admission process in 7-15 days instead of months of waiting.' },
            { icon: '🏅', title: 'Merit-Based', text: 'Admission based on your complete profile — academics, experience, and potential.' },
            { icon: '✅', title: 'Guaranteed Seat', text: 'Secure confirmed admission without the uncertainty of competitive selections.' },
            { icon: '🏛️', title: 'Top Colleges', text: 'Direct admission available in NAAC A/A+ graded and NBA-accredited institutions.' },
            { icon: '🎯', title: 'Profile Matching', text: 'AI-powered college recommendations based on your unique profile strengths.' },
            { icon: '📞', title: 'Dedicated Support', text: 'Personal admission counselor assigned to guide you through every step.' },
        ],
        curriculum: [
            'Principles of Management & Organizational Behavior',
            'Accounting for Managers & Corporate Finance',
            'Marketing Management & Consumer Analytics',
            'Human Resource Development & Talent Management',
            'Business Law & Corporate Ethics',
            'Supply Chain & Logistics Management',
            'Digital Business & E-commerce Management',
            'Capstone Project & Industry Dissertation',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (Full-time)' },
            { icon: '📋', label: 'Degree Type', value: 'MBA / PGDM' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'Optional / Merit-based' },
            { icon: '💰', label: 'Fee Range', value: '₹4L - ₹20L (Varies)' },
            { icon: '🎯', label: 'Process Duration', value: '7-15 Business Days' },
        ],
        whyChoose: [
            'Avoid the stress and uncertainty of highly competitive entrance exam-based admissions',
            'Ideal for working professionals who want a guaranteed admission with minimal disruption',
            'Faster admission process — get confirmed within 2 weeks of application',
            'Bschool Bridge partners only with accredited, transparent institutions for direct admission',
            'Suitable for candidates with strong profiles but modest entrance exam scores',
            'Holistic evaluation considers your complete profile, not just one exam score',
        ],
        sortOrder: 4,
    },
    {
        slug: 'executive-mba',
        title: 'Executive MBA',
        subtitle: 'Accelerate your career with Executive MBA programs designed for working professionals — study on weekends while you continue working.',
        icon: '💼',
        badge: 'For Professionals',
        shortDesc: 'Advance your career with weekend and part-time MBA programs designed for working professionals.',
        duration: '1-2 Years',
        mode: 'Part-time',
        gradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        heroGradient: 'linear-gradient(135deg, #8b5cf6, #a855f7)',
        navDesc: 'For working professionals',
        overview: [
            "The Executive MBA (EMBA) is a premium management program specifically designed for mid-career professionals who want to advance to senior leadership positions without leaving their jobs. It combines rigorous academic learning with practical business application.",
            'Executive MBA programs offer flexible scheduling — weekend classes, evening sessions, or intensive module-based formats — so that professionals can balance work, studies, and personal life effectively.',
            "Bschool Bridge connects experienced professionals with India's top Executive MBA programs at institutions like ISB, IIMs, XLRI, and Great Lakes, ensuring you find the perfect program for your career stage and aspirations.",
        ],
        eligibility: [
            "Bachelor's degree from a recognized university with minimum 50% marks",
            'Minimum 3-5 years of full-time professional work experience (varies by institution)',
            'Currently employed professionals preferred by most Executive MBA programs',
            'GMAT/GRE scores may be required for top-tier programs (ISB, IIMs)',
            'Strong professional track record with demonstrated career progression',
            'Employer sponsorship or self-financing capability',
        ],
        highlights: [
            { icon: '📅', title: 'Weekend Classes', text: 'Study on weekends or in intensive module format without leaving your job.' },
            { icon: '🏢', title: 'Peer Network', text: 'Learn alongside experienced professionals from diverse industries and functions.' },
            { icon: '📈', title: 'Career Growth', text: 'Average 60% salary increase within 2 years of completing Executive MBA.' },
            { icon: '🌐', title: 'Global Modules', text: 'International immersion modules at partner universities in USA, Europe, and Asia.' },
            { icon: '👨‍🏫', title: 'Senior Faculty', text: 'Learn from world-class faculty with corporate consulting experience.' },
            { icon: '🤝', title: 'C-Suite Access', text: 'Networking opportunities with CEOs, founders, and industry leaders.' },
        ],
        curriculum: [
            'Strategic Leadership & Change Management',
            'Corporate Strategy & Competitive Advantage',
            'Advanced Financial Management & Valuation',
            'Digital Transformation & Technology Management',
            'Global Business Strategy & International Markets',
            'Mergers, Acquisitions & Corporate Restructuring',
            'Innovation Management & Design Thinking',
            'Executive Communication & Negotiation',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '1-2 Years' },
            { icon: '📋', label: 'Degree Type', value: 'Executive MBA / PGPX' },
            { icon: '📍', label: 'Mode', value: 'Weekend / Modular' },
            { icon: '📝', label: 'Experience Required', value: '3-5+ Years' },
            { icon: '💰', label: 'Fee Range', value: '₹15L - ₹40L (Varies)' },
            { icon: '🎯', label: 'Salary Hike', value: '40-80% Average' },
        ],
        whyChoose: [
            'Continue earning your salary while pursuing a world-class MBA education',
            'Immediate application of classroom learnings to your current job responsibilities',
            'Build an elite network of experienced professionals across industries',
            'Strong ROI — Executive MBA graduates see the fastest salary progression',
            'Employer-sponsored options available at many partner institutions',
            'Globally recognized credentials that open doors to CXO-level positions',
        ],
        sortOrder: 5,
    },
    {
        slug: 'distance-online-mba',
        title: 'Distance / Online MBA',
        subtitle: "Earn a UGC-recognized MBA degree from top universities through distance or online learning — study anytime, anywhere at your own pace.",
        icon: '🌐',
        badge: 'UGC Approved',
        shortDesc: 'Study from anywhere with UGC-recognized distance and online MBA programs from top universities.',
        duration: '2 Years',
        mode: 'Online',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        heroGradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        navDesc: 'Learn from anywhere',
        overview: [
            "Distance and Online MBA programs offer a flexible and affordable pathway to earn a management degree from some of India's most reputed universities without attending regular classes. These programs are recognized by UGC-DEB (University Grants Commission - Distance Education Bureau) and are valid for all job applications.",
            'With advancements in educational technology, online MBA programs now offer interactive live classes, recorded lectures, virtual labs, discussion forums, and digital libraries — providing an experience that closely mirrors on-campus learning.',
            'Bschool Bridge helps you choose from UGC-approved distance and online MBA programs offered by institutions like IGNOU, Amity Online, Manipal Online, Symbiosis SCDL, and many more.',
        ],
        eligibility: [
            "Bachelor's degree from a recognized university with minimum 50% marks",
            'No entrance exam required for most distance/online MBA programs',
            'Working professionals, homemakers, and entrepreneurs are all eligible',
            'No upper age limit for most distance learning programs',
            'Basic computer literacy and internet access required for online programs',
        ],
        highlights: [
            { icon: '🏠', title: 'Study From Home', text: 'No relocation needed — attend classes online from the comfort of your home.' },
            { icon: '💰', title: 'Affordable', text: 'Fee as low as ₹50,000 - ₹2,00,000 for the entire 2-year program.' },
            { icon: '🎓', title: 'UGC Recognized', text: 'All partner programs are UGC-DEB approved and valid for government jobs.' },
            { icon: '⏰', title: 'Flexible Schedule', text: 'Self-paced learning with recorded lectures — study when it suits you.' },
            { icon: '💼', title: 'Work & Learn', text: 'Perfect for working professionals who cannot attend full-time programs.' },
            { icon: '📱', title: 'Digital Learning', text: 'Access courses via mobile app, live classes, and interactive learning platforms.' },
        ],
        curriculum: [
            'Principles of Management & Business Communication',
            'Managerial Accounting & Financial Management',
            'Marketing Management & Digital Marketing',
            'Human Resource Management & Organizational Behavior',
            'Business Research Methods & Strategy',
            'Operations Management & Project Management',
            'International Business & Economic Environment',
            'Elective Specialization (Finance / Marketing / HR / IT)',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (Flexible)' },
            { icon: '📋', label: 'Degree Type', value: 'MBA (UGC-DEB Approved)' },
            { icon: '📍', label: 'Mode', value: 'Online / Distance' },
            { icon: '📝', label: 'Entrance Exams', value: 'Not Required' },
            { icon: '💰', label: 'Fee Range', value: '₹50K - ₹2L (Total)' },
            { icon: '🎯', label: 'EMI Available', value: 'Yes, 0% Interest' },
        ],
        whyChoose: [
            'Most affordable way to earn an MBA degree from a reputed university',
            'UGC-DEB recognition ensures your degree is valid for all employment opportunities',
            'No need to quit your job or relocate — study at your convenience',
            'Same curriculum and faculty as regular MBA in many universities',
            'EMI options available making education financially accessible to everyone',
            'Ideal for tier-2/3 city students who lack access to quality B-schools locally',
        ],
        sortOrder: 6,
    },
];

const specializationsData = [
    {
        slug: 'mba-marketing',
        title: 'MBA in Marketing',
        subtitle: 'Master the art and science of marketing with an MBA specialization that prepares you for leadership roles in brand management, digital marketing, and consumer strategy.',
        icon: '📢',
        badge: 'Most Popular',
        shortDesc: 'Brand & digital strategy',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #f97316, #ef4444)',
        heroGradient: 'linear-gradient(135deg, #f97316, #ef4444)',
        navDesc: 'Brand & digital strategy',
        overview: [
            "An MBA in Marketing is one of the most popular and dynamic specializations in the business world. It equips students with deep knowledge of consumer behavior, brand strategy, market research, digital marketing, advertising, and sales management — all essential skills for driving business growth in today's competitive landscape.",
            'Marketing professionals are in high demand across every industry — from FMCG and retail to technology, healthcare, and financial services. With the rapid growth of digital channels, the scope of marketing has expanded dramatically, creating exciting career opportunities in performance marketing, content strategy, social media management, and marketing analytics.',
            'At Bschool Bridge, we connect you with top-ranked MBA programs specializing in marketing, offered by premier B-schools known for strong industry connections and outstanding placement records in marketing roles.',
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, MAT, CMAT, or equivalent',
            'Strong communication and creative thinking skills are advantageous',
            'Work experience in sales, marketing, or advertising is a plus but not mandatory',
            'Final year graduation students can also apply',
        ],
        highlights: [
            { icon: '📊', title: 'Brand Management', text: 'Learn to build, manage, and grow iconic brands across traditional and digital channels.' },
            { icon: '📱', title: 'Digital Marketing', text: 'Master SEO, SEM, social media, content marketing, and performance marketing strategies.' },
            { icon: '🎯', title: 'Consumer Insights', text: 'Understand consumer psychology, behavior patterns, and data-driven decision making.' },
            { icon: '💰', title: 'High ROI Careers', text: 'Marketing MBAs command salaries of ₹8-30 LPA in top companies across India.' },
            { icon: '🌐', title: 'Global Opportunities', text: 'Marketing skills are universally valued — work anywhere in the world.' },
            { icon: '🏆', title: 'Leadership Roles', text: 'Fast-track to CMO, VP Marketing, and Brand Director positions.' },
        ],
        curriculum: [
            'Marketing Management & Consumer Behavior',
            'Brand Management & Advertising Strategy',
            'Digital Marketing & Social Media Marketing',
            'Sales & Distribution Management',
            'Market Research & Marketing Analytics',
            'Retail Management & E-commerce Strategy',
            'Integrated Marketing Communications (IMC)',
            'Product Management & Innovation',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Marketing Management' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, GMAT, MAT' },
            { icon: '💰', label: 'Avg. Package', value: '₹8-30 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'HUL, P&G, Amazon, Google' },
        ],
        whyChoose: [
            'Marketing is the largest recruiter at most top B-schools with the most diverse career options',
            'Combines creativity with analytics — ideal for both left-brain and right-brain thinkers',
            'Digital transformation has created massive demand for marketing-savvy MBAs',
            'Offers entrepreneurial pathways — many successful startups are founded by marketing MBAs',
            'Excellent opportunities in emerging fields like influencer marketing, MarTech, and growth hacking',
            'Strong alumni networks in marketing provide lifelong career support and mentorship',
        ],
        sortOrder: 1,
    },
    {
        slug: 'mba-finance',
        title: 'MBA in Finance',
        subtitle: "Build a high-impact career in investment banking, corporate finance, and financial analytics with an MBA in Finance from India's top B-schools.",
        icon: '💹',
        badge: 'Highest Packages',
        shortDesc: 'Investment & corporate finance',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #10b981, #059669)',
        heroGradient: 'linear-gradient(135deg, #10b981, #059669)',
        navDesc: 'Investment & corporate finance',
        overview: [
            "An MBA in Finance India is among the most prestigious and rewarding specializations in management education. It prepares students for leadership roles in banking, investment management, corporate finance, financial consulting, and fintech — sectors that form the backbone of any economy.",
            "Finance professionals are critical to every organization. Whether it's a multinational corporation managing billions in assets, a startup seeking venture capital, or a government body designing fiscal policy, MBA Finance graduates are at the forefront of strategic financial decision-making.",
            "India's financial services industry is projected to grow to $1.5 trillion by 2025, creating unprecedented demand for finance professionals. At Bschool Bridge, we guide you to the best MBA in Finance programs in India — from IIM Ahmedabad and IIM Bangalore to ISB, XLRI, and FMS Delhi — ensuring you gain the skills and credentials to excel in this highly competitive field.",
        ],
        eligibility: [
            "Bachelor's degree in any discipline (Commerce/Science/Engineering preferred) with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, CMAT, SNAP, or NMAT',
            'Strong quantitative aptitude and analytical reasoning skills',
            'CFA, CA, or CMA certifications can enhance your profile significantly',
            'Work experience in banking, accounting, or financial services is advantageous',
        ],
        highlights: [
            { icon: '🏦', title: 'Investment Banking', text: 'Prepare for roles at Goldman Sachs, JP Morgan, Morgan Stanley, and top Indian banks.' },
            { icon: '📈', title: 'Highest Packages', text: 'MBA Finance graduates earn among the highest salaries — ₹12-50 LPA at top B-schools.' },
            { icon: '💎', title: 'CFA Integration', text: 'Many programs integrate CFA curriculum, giving you dual credentials.' },
            { icon: '🔢', title: 'Financial Analytics', text: 'Master financial modeling, risk assessment, derivatives, and algorithmic trading.' },
            { icon: '🌍', title: 'Global Finance Hubs', text: 'Opportunities in Mumbai, Singapore, Dubai, London, and New York.' },
            { icon: '🚀', title: 'Fintech Revolution', text: 'Lead innovation in digital payments, blockchain, robo-advisory, and InsurTech.' },
        ],
        curriculum: [
            'Corporate Finance & Financial Management',
            'Investment Analysis & Portfolio Management',
            'Financial Accounting & Reporting',
            'Banking & Insurance Management',
            'Derivatives & Risk Management',
            'Mergers, Acquisitions & Corporate Restructuring',
            'Financial Modeling & Valuation',
            'Fintech, Blockchain & Digital Finance',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Finance Management' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, GMAT, SNAP' },
            { icon: '💰', label: 'Avg. Package', value: '₹12-50 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'Goldman Sachs, Deloitte, EY' },
        ],
        whyChoose: [
            'MBA in Finance India offers the highest ROI with starting salaries of ₹12-50 LPA at top B-schools',
            'Finance is a recession-proof career — financial expertise is needed in every economic condition',
            'Opens doors to prestigious roles in investment banking, private equity, and venture capital',
            "India's growing fintech ecosystem offers unique entrepreneurial opportunities for finance MBAs",
            'CFA-aligned programs provide globally recognized credentials alongside your MBA degree',
            'Strong analytical foundation enables easy transition to consulting, analytics, or C-suite roles',
        ],
        sortOrder: 2,
    },
    {
        slug: 'mba-hr',
        title: 'MBA in Human Resources',
        subtitle: "Shape organizational culture and drive talent strategy with an MBA in HR from India's leading B-schools and MBA HR colleges known for exceptional placements.",
        icon: '👥',
        badge: 'People Strategy',
        shortDesc: 'People & talent management',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        heroGradient: 'linear-gradient(135deg, #8b5cf6, #6366f1)',
        navDesc: 'People & talent management',
        overview: [
            "An MBA in Human Resources (HR) is a specialized management program that prepares students to lead the people function in organizations. From talent acquisition and employee engagement to organizational development and HR analytics, this specialization covers every aspect of managing an organization's most valuable asset — its people.",
            'The demand for skilled HR professionals has surged as companies recognize that people strategy directly impacts business performance. Modern HR goes far beyond traditional personnel management — it now encompasses employer branding, people analytics, diversity & inclusion, HR technology, and strategic workforce planning.',
            "Top MBA HR colleges in India — including XLRI Jamshedpur, TISS Mumbai, IIM Ranchi, MDI Gurgaon, and SCMHRD Pune — are renowned for producing India's finest HR leaders. Bschool Bridge helps you secure admission to these premier MBA HR colleges, ensuring you receive world-class education and access to the best HR placement opportunities in the country.",
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, MAT, or institution-specific tests like XAT for XLRI',
            'Strong interpersonal and communication skills are highly valued',
            'Psychology, sociology, or liberal arts background can be advantageous',
            'Work experience in HR, recruitment, or people management is a plus for executive programs',
        ],
        highlights: [
            { icon: '🎯', title: 'Strategic HR', text: 'Learn to align HR strategy with business objectives for maximum organizational impact.' },
            { icon: '📊', title: 'People Analytics', text: 'Master HR analytics, workforce planning, and data-driven people decisions.' },
            { icon: '🏛️', title: 'Top HR Colleges', text: 'Admission support for XLRI, TISS, IIM Ranchi, MDI, and other top MBA HR colleges.' },
            { icon: '💼', title: 'CHRO Pipeline', text: 'Fast-track path to CHRO, VP-HR, and Head of People roles at leading companies.' },
            { icon: '🌱', title: 'Culture Building', text: 'Learn to design and sustain high-performance organizational cultures.' },
            { icon: '🤖', title: 'HR Tech', text: 'Explore AI in recruitment, HR automation, and emerging HR technology platforms.' },
        ],
        curriculum: [
            'Human Resource Management & Organizational Behavior',
            'Talent Acquisition & Employer Branding',
            'Compensation & Benefits Management',
            'Labor Laws & Industrial Relations',
            'HR Analytics & People Data Science',
            'Learning & Development (L&D) Strategy',
            'Performance Management & Employee Engagement',
            'Organizational Development & Change Management',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Human Resources' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, GMAT, MAT' },
            { icon: '💰', label: 'Avg. Package', value: '₹10-28 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'Aon, Deloitte, Accenture' },
        ],
        whyChoose: [
            "MBA HR colleges in India like XLRI and TISS produce the country's most sought-after HR leaders",
            'HR is a function that exists in every organization — ensuring consistent demand for HR MBAs',
            'Modern HR combines psychology, business strategy, and technology — a unique and fulfilling blend',
            'CHRO is one of the fastest-growing C-suite roles with compensation matching that of CFOs and CMOs',
            'HR analytics and HR tech are emerging fields offering cutting-edge career opportunities',
            'Strong work-life balance compared to other management specializations like investment banking',
        ],
        sortOrder: 3,
    },
    {
        slug: 'mba-business-analytics',
        title: 'MBA in Business Analytics',
        subtitle: 'Harness the power of data to drive business decisions with an MBA in Business Analytics — the fastest-growing specialization in management education.',
        icon: '📊',
        badge: 'Fastest Growing',
        shortDesc: 'Data-driven decisions',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #0ea5e9, #3b82f6)',
        heroGradient: 'linear-gradient(135deg, #0ea5e9, #3b82f6)',
        navDesc: 'Data-driven decisions',
        overview: [
            'An MBA in Business Analytics combines the rigor of data science with the strategic thinking of an MBA. As organizations worldwide adopt data-driven decision-making, the demand for professionals who can translate complex data into actionable business insights has skyrocketed.',
            "This specialization teaches you advanced statistical analysis, machine learning, predictive modeling, data visualization, and business intelligence — all within the context of real-world business challenges. You'll learn to use tools like Python, R, SQL, Tableau, Power BI, and cloud-based analytics platforms.",
            'Top B-schools like IIM Calcutta, ISB Hyderabad, IIM Bangalore, and Great Lakes have launched dedicated Business Analytics programs to meet industry demand. At Bschool Bridge, we help you choose the right analytics program based on your background and career goals.',
        ],
        eligibility: [
            "Bachelor's degree in any discipline (Engineering/Science/Commerce preferred) with minimum 50% marks",
            'Valid entrance exam score — CAT, GMAT, GRE, or program-specific analytics aptitude tests',
            'Strong quantitative and logical reasoning abilities',
            'Basic programming knowledge (Python/R) is advantageous but not mandatory',
            'Work experience in IT, consulting, or analytics roles strengthens your application',
        ],
        highlights: [
            { icon: '🤖', title: 'AI & Machine Learning', text: 'Master supervised/unsupervised learning, deep learning, and NLP for business applications.' },
            { icon: '💼', title: 'Highest Demand', text: 'Analytics roles are growing at 30% annually — one of the fastest in any industry globally.' },
            { icon: '📈', title: 'Premium Salaries', text: 'Analytics MBAs command ₹12-40 LPA with top companies in India and abroad.' },
            { icon: '🔬', title: 'Hands-on Learning', text: 'Capstone projects with real company data from partners like Amazon, Flipkart, and Microsoft.' },
            { icon: '🌐', title: 'Cross-Industry Demand', text: 'Every industry needs analytics — healthcare, finance, retail, tech, and more.' },
            { icon: '🏅', title: 'Future-Proof Career', text: 'Data and AI are the foundation of all future business — your skills will always be relevant.' },
        ],
        curriculum: [
            'Statistics & Probability for Business',
            'Data Mining & Predictive Analytics',
            'Machine Learning & Artificial Intelligence',
            'Big Data Technologies (Hadoop, Spark)',
            'Business Intelligence & Data Visualization',
            'Marketing Analytics & Customer Analytics',
            'Financial Analytics & Risk Modeling',
            'Supply Chain Analytics & Operations Research',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Business Analytics' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, GMAT, GRE' },
            { icon: '💰', label: 'Avg. Package', value: '₹12-40 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'McKinsey, Amazon, Microsoft' },
        ],
        whyChoose: [
            'Business Analytics is the #1 emerging MBA specialization with the highest growth in demand',
            'Bridges the gap between technical data science and business strategy — a unique niche',
            'Analytics professionals are among the highest-paid across all management functions',
            'Skills in data and AI are transferable across every industry and geography',
            'Strong entrepreneurial potential — many data-driven startups are founded by analytics MBAs',
            'Future-proof career path as organizations increasingly rely on data for every decision',
        ],
        sortOrder: 4,
    },
    {
        slug: 'mba-operations',
        title: 'MBA in Operations Management',
        subtitle: 'Drive operational excellence and supply chain efficiency with an MBA in Operations — the backbone of every successful organization.',
        icon: '⚙️',
        badge: 'Industry 4.0',
        shortDesc: 'Supply chain & logistics',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
        heroGradient: 'linear-gradient(135deg, #f59e0b, #d97706)',
        navDesc: 'Supply chain & logistics',
        overview: [
            'An MBA in Operations Management prepares you to optimize business processes, manage supply chains, and drive efficiency across organizations. Operations managers ensure that products are manufactured, services are delivered, and resources are allocated in the most efficient and cost-effective manner possible.',
            "With the rise of global supply chains, e-commerce logistics, Industry 4.0, and lean manufacturing, the demand for operations professionals has never been higher. Companies like Amazon, Flipkart, Tata Motors, and Reliance actively seek MBA operations graduates to manage their complex operational ecosystems.",
            "Top B-schools including IIM Ahmedabad, IIT Bombay's SJMSOM, NITIE Mumbai (now IIM Mumbai), and IIM Udaipur are renowned for their operations management programs. Bschool Bridge connects you with the best programs based on your career aspirations.",
        ],
        eligibility: [
            "Bachelor's degree in any discipline (Engineering background preferred) with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, CMAT, or equivalent',
            'Analytical thinking and problem-solving aptitude',
            'Work experience in manufacturing, supply chain, or logistics is advantageous',
            'Six Sigma, Lean, or PMP certifications can strengthen your profile',
        ],
        highlights: [
            { icon: '🏭', title: 'Industry 4.0', text: 'Learn smart manufacturing, IoT, robotics, and digital twin technologies.' },
            { icon: '🚛', title: 'Supply Chain', text: 'Master end-to-end supply chain management, procurement, and logistics optimization.' },
            { icon: '📉', title: 'Lean & Six Sigma', text: 'Become certified in Lean Manufacturing and Six Sigma methodologies.' },
            { icon: '🎯', title: 'Process Excellence', text: 'Learn to design, optimize, and automate business processes for maximum efficiency.' },
            { icon: '🌐', title: 'Global Ops', text: 'Manage international supply chains, global sourcing, and cross-border logistics.' },
            { icon: '💼', title: 'Diverse Roles', text: 'Roles in consulting, manufacturing, logistics, e-commerce, and technology firms.' },
        ],
        curriculum: [
            'Operations Management & Production Planning',
            'Supply Chain Management & Logistics',
            'Quality Management & Six Sigma',
            'Project Management & Agile Methodology',
            'Operations Research & Optimization',
            'Procurement & Vendor Management',
            'Industry 4.0 & Smart Manufacturing',
            'Service Operations & Capacity Planning',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Operations Management' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, XAT, GMAT' },
            { icon: '💰', label: 'Avg. Package', value: '₹10-30 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'Amazon, Tata, Mahindra' },
        ],
        whyChoose: [
            'Operations is the backbone of business — every company needs operations professionals',
            'E-commerce boom has created massive demand for supply chain and logistics managers',
            'Excellent work-life balance compared to B-school peers in consulting or investment banking',
            'Industry 4.0 and smart manufacturing are creating exciting new career opportunities',
            'Operations MBAs are well-positioned for CEO roles — many Fortune 500 CEOs have ops backgrounds',
            'Six Sigma and Lean certifications add globally recognized credentials to your MBA',
        ],
        sortOrder: 5,
    },
    {
        slug: 'mba-digital-marketing',
        title: 'MBA in Digital Marketing',
        subtitle: 'Lead the digital revolution with an MBA in Digital Marketing — the most in-demand specialization for the new age of business and consumer engagement.',
        icon: '📱',
        badge: 'Trending',
        shortDesc: 'SEO, SEM & social media',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        heroGradient: 'linear-gradient(135deg, #ec4899, #f43f5e)',
        navDesc: 'SEO, SEM & social media',
        overview: [
            "An MBA in Digital Marketing is the fastest-growing specialization in management education, driven by the explosive growth of digital platforms, e-commerce, and online consumer behavior. This program combines traditional marketing strategy with cutting-edge digital skills including SEO, SEM, social media marketing, content strategy, marketing automation, and advanced analytics.",
            "India's digital advertising market is growing at 30%+ annually, and every company — from startups to Fortune 500 — is investing heavily in digital transformation. An MBA digital marketing degree prepares you to lead this transformation, whether you're managing a brand's social media presence, running multi-million dollar performance campaigns, or building a company's entire digital strategy.",
            'Top institutions offering MBA digital marketing programs include MICA Ahmedabad, IIM Indore, Symbiosis (SCMC Pune), Mudra Institute, and several AICTE-approved colleges with industry-linked digital marketing curricula. Bschool Bridge helps you find the right MBA digital marketing program based on your career goals, budget, and city preference.',
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, MAT, MICAT, or university-specific tests',
            'Passion for digital platforms, content creation, and online consumer behavior',
            'Basic understanding of social media and digital tools is advantageous',
            'Google Ads, HubSpot, or Meta certifications can strengthen your application',
        ],
        highlights: [
            { icon: '🔍', title: 'SEO & SEM Mastery', text: 'Master search engine optimization and paid search to drive organic and paid growth.' },
            { icon: '📣', title: 'Social Media Strategy', text: 'Design and execute campaigns across Instagram, LinkedIn, YouTube, and emerging platforms.' },
            { icon: '📧', title: 'Marketing Automation', text: 'Learn HubSpot, Marketo, and Salesforce for automated customer journey management.' },
            { icon: '📈', title: 'Performance Marketing', text: 'Run data-driven Google Ads, Meta Ads, and programmatic campaigns at scale.' },
            { icon: '🎨', title: 'Content Strategy', text: 'Create compelling content strategies for blogs, video, podcasts, and email marketing.' },
            { icon: '🤖', title: 'AI in Marketing', text: 'Leverage AI tools for personalization, chatbots, predictive targeting, and creative generation.' },
        ],
        curriculum: [
            'Digital Marketing Strategy & Planning',
            'Search Engine Optimization (SEO) & Content Marketing',
            'Pay-Per-Click (PPC) & Performance Marketing',
            'Social Media Marketing & Influencer Strategy',
            'Email Marketing & Marketing Automation',
            'Web Analytics, Google Analytics & Data Studio',
            'E-commerce Marketing & Conversion Optimization',
            'AI in Marketing & MarTech Stack Management',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'Digital Marketing' },
            { icon: '📍', label: 'Mode', value: 'Full-time / Hybrid' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, MICAT, XAT, MAT' },
            { icon: '💰', label: 'Avg. Package', value: '₹8-25 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'Google, Meta, Dentsu, WPP' },
        ],
        whyChoose: [
            'MBA digital marketing is the fastest-growing specialization with 30%+ annual growth in job openings',
            "Every company needs digital marketing — ensuring you're never short of career opportunities",
            'Perfect blend of creativity and technology for those who love both storytelling and analytics',
            'High freelancing and entrepreneurial potential — start your own digital agency after graduation',
            'Constantly evolving field means your career will never be boring — always learning something new',
            'Global demand for digital marketing professionals makes relocation and remote work easy',
        ],
        sortOrder: 6,
    },
    {
        slug: 'mba-international-business',
        title: 'MBA in International Business',
        subtitle: 'Go global with an MBA in International Business — master cross-border trade, global strategy, and international market expansion.',
        icon: '🌍',
        badge: 'Go Global',
        shortDesc: 'Global trade & strategy',
        duration: '2 Years',
        mode: 'Full-time',
        gradient: 'linear-gradient(135deg, #06b6d4, #0284c7)',
        heroGradient: 'linear-gradient(135deg, #06b6d4, #0284c7)',
        navDesc: 'Global trade & strategy',
        overview: [
            'An MBA in International Business prepares you to navigate the complexities of global commerce, cross-cultural management, and international market strategy. As Indian companies expand globally and multinational corporations deepen their India operations, the demand for professionals with international business acumen has never been higher.',
            'This specialization covers international trade policy, export-import management, foreign exchange, cross-cultural negotiations, global supply chain management, and international marketing — giving you a 360-degree understanding of how business operates across borders.',
            'Premier institutions like IIFT Delhi, IIM Lucknow, Symbiosis SIIB, Amity International Business School, and Christ University offer specialized MBA International Business programs. Bschool Bridge helps you identify the best program based on your career goals — whether you aim to work with global MNCs, Indian companies going overseas, or international trade organizations.',
        ],
        eligibility: [
            "Bachelor's degree in any discipline from a recognized university with minimum 50% marks",
            'Valid entrance exam score — CAT, XAT, GMAT, IIFT exam, or equivalent',
            'Strong communication skills and cross-cultural awareness',
            'Foreign language proficiency (French, German, Spanish, Mandarin) is a plus',
            'International exposure through travel, internships, or exchange programs is advantageous',
        ],
        highlights: [
            { icon: '✈️', title: 'Global Exposure', text: 'International exchange programs, foreign university semesters, and global study tours.' },
            { icon: '🏛️', title: 'Trade & Policy', text: 'Deep understanding of WTO, trade agreements, tariffs, and international trade law.' },
            { icon: '💱', title: 'Forex & Finance', text: 'Master foreign exchange management, international finance, and cross-border M&A.' },
            { icon: '🤝', title: 'Cross-Cultural Skills', text: 'Learn to manage diverse teams, negotiate across cultures, and build global partnerships.' },
            { icon: '📦', title: 'Global Supply Chain', text: 'Design and manage international supply chains, logistics, and distribution networks.' },
            { icon: '🌐', title: 'Expat Opportunities', text: 'Opportunities for international postings in MNCs across US, Europe, Middle East, and Southeast Asia.' },
        ],
        curriculum: [
            'International Business Environment & Strategy',
            'Export-Import Management & Trade Finance',
            'International Marketing & Cross-Cultural Consumer Behavior',
            'Foreign Exchange & International Financial Management',
            'Global Supply Chain & Logistics Management',
            'International Human Resource Management',
            'International Trade Law & WTO Regulations',
            'Emerging Markets & Country Risk Analysis',
        ],
        sidebarInfo: [
            { icon: '⏱️', label: 'Duration', value: '2 Years (4 Semesters)' },
            { icon: '📋', label: 'Specialization', value: 'International Business' },
            { icon: '📍', label: 'Mode', value: 'Full-time, On-campus' },
            { icon: '📝', label: 'Entrance Exams', value: 'CAT, IIFT, XAT, GMAT' },
            { icon: '💰', label: 'Avg. Package', value: '₹10-30 LPA' },
            { icon: '🎯', label: 'Top Recruiters', value: 'KPMG, EY, Citi, Nestle' },
        ],
        whyChoose: [
            'Growing India-global trade (target $2 trillion by 2030) is creating massive demand for IB professionals',
            'Opportunity for international postings, global travel, and expatriate packages from day one',
            'Unique skills in cross-cultural management that cannot be easily automated or replaced',
            'IIFT Delhi and IIM programs have exceptional 100% placement records in international business',
            'Opens doors to careers in diplomacy, international organizations (UN, World Bank), and trade bodies',
            'Dual-degree opportunities with foreign universities add international credentials to your resume',
        ],
        sortOrder: 7,
    },
];

async function seedServicesAndSpecializations() {
    try {
        // Check if data already exists
        const existingServices = await Service.countDocuments();
        const existingSpecs = await Specialization.countDocuments();

        if (existingServices === 0) {
            await Service.insertMany(servicesData);
            console.log(`✅ Seeded ${servicesData.length} services`);
        } else {
            console.log(`ℹ️  Services already exist (${existingServices} found), skipping seed`);
        }

        if (existingSpecs === 0) {
            await Specialization.insertMany(specializationsData);
            console.log(`✅ Seeded ${specializationsData.length} specializations`);
        } else {
            console.log(`ℹ️  Specializations already exist (${existingSpecs} found), skipping seed`);
        }
    } catch (error) {
        console.error('❌ Error seeding services/specializations:', error.message);
    }
}

module.exports = seedServicesAndSpecializations;
